version: '3.7'

services:

  application:
    container_name: text-counter-app
    build: .
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "9090:8080"
    networks:
      - text-counter-network

  zookeeper:
    container_name: text-counter-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - text-counter-network

  kafka:
    container_name: text-counter-kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "TopicA:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - text-counter-network

networks:
  text-counter-network:
    name: text-counter-network
